# Generated by Django 3.2.7 on 2021-09-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(default=' ', max_length=50)),
                ('status', models.CharField(default=' ', max_length=50)),
                ('price', models.CharField(default=' ', max_length=50)),
                ('condition', models.CharField(default=' ', max_length=50)),
                ('picture', models.CharField(default=' ', max_length=50)),
                ('year_manufactured', models.CharField(default=' ', max_length=50)),
                ('make', models.CharField(default=' ', max_length=50)),
                ('model', models.CharField(default=' ', max_length=50)),
                ('trim', models.CharField(default=' ', max_length=50)),
                ('body_style', models.CharField(default=' ', max_length=50)),
                ('mileage', models.CharField(default=' ', max_length=50)),
                ('fuel_type', models.CharField(default=' ', max_length=50)),
                ('mpg', models.CharField(default=' ', max_length=50)),
                ('interior_color', models.CharField(default=' ', max_length=50)),
                ('exterior_color', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
